import {
  Activity,
  AlertTriangle,
  Baby,
  Biohazard,
  Bone,
  Bug,
  Car,
  CircleAlert,
  Cog,
  Droplet,
  Flame,
  FlaskConical,
  Frown,
  HeartPulse,
  Brain,
  Meh,
  RotateCw,
  Scissors,
  Snowflake,
  Thermometer,
  TrendingDown,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "non-trauma-shock": Activity,
  "airway-obstruction": Wind,
  dyspnea: Wind,
  hyperventilation: Wind,
  "chest-pain": HeartPulse,
  bradycardia: HeartPulse,
  tachycardia: HeartPulse,
  syncope: Activity,
  hemoptysis: Droplet,
  "gi-bleeding": Droplet,
  "altered-mental-status": Brain,
  stroke: Brain,
  seizure: Zap,
  hypoglycemia: Droplet,
  fever: Thermometer,
  "sepsis-shock": Biohazard,
  "abdominal-pain": Frown,
  "nausea-vomiting": Meh,
  diarrhea: Droplet,
  dizziness: RotateCw,
  anaphylaxis: AlertTriangle,
  "behavioral-emergency": Brain,
  childbirth: Baby,
  "vaginal-bleeding": Droplet,
  eclampsia: Baby,

  "traffic-accident": Car,
  "fall-trauma": AlertTriangle,
  "fall-from-height": TrendingDown,
  "multi-trauma": AlertTriangle,
  "head-injury": Brain,
  "spine-injury": Bone,
  "chest-injury": HeartPulse,
  "abdomen-pelvis-injury": CircleAlert,
  "limb-injury": Bone,
  "blunt-injury": CircleAlert,
  laceration: Scissors,
  "stab-penetrating": Scissors,
  "machinery-injury": Cog,
  burn: Flame,
  "electrical-injury": Zap,
  poisoning: FlaskConical,
  drowning: Waves,
  asphyxiation: Wind,
  hypothermia: Snowflake,
  "heat-illness": Thermometer,
  "animal-bite": Bug,
};

export function getScenarioIcon(slug: string): LucideIcon {
  return iconMap[slug] ?? CircleAlert;
}
